name: Daily Bot Auto Commit

on:
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot-auto-commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REPO_BRANCH: ${{ github.ref_name }}
          TIMES: '20'
          AUTHOR_NAME: 'Tenica'
          AUTHOR_EMAIL: '231294492+Nhqvu2005@users.noreply.github.com'
        run: |
          python bot-auto-commit.py

